### ISSUE TITLE
duplication of entries

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/geo-uploader-cli#29] opened 2019-07-02 12:16 UTC
the tool also duplicates the samples

**Comment by qbicStefanC** [comment] 2019-07-02 12:17
sample info and samples are duplicated,actually

**Comment by lucast122** [comment] 2019-07-02 16:14
This behaviour was intended for paired end samples as they have 2 different raw file names.
For paired end samples: Would you prefer each sample being written down twice once for each raw file or would you prefer it to be written down only once just for one of the raw files?
I will fix this for single end samples as it makes absolutely no sense there

**Comment by qbicStefanC** [comment] 2019-07-03 07:09
There should be just one lane for each sample. In case of paired end experiment the column raw file of the SAMPLES section should be duplicated (see EXAMPLE 2 excel tab of the template).

**Comment by lucast122** [comment] 2019-07-03 18:55
fixed with #37

**Closed as completed** 2019-07-04 20:34 UTC
